import Head from 'next/head';
import { Header } from '@/components/Header';
import { Course } from '@/components/Course';
import { Topics } from '@/components/Topics';
import { MainVideo } from '@/components/MainVideo';
import { TestimonialsBlue } from '@/components/TestimonialsBlue';
import { TestimonialsWhite } from '@/components/TestimonialsWhite';

export default function Home() {
  return (
    <>
      <Head>
        <title>Site de Vendas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/" /> */}
      </Head>
      <Header />
      <Course />
      <Topics />
      <MainVideo />
      <TestimonialsBlue />
      <TestimonialsWhite />
      <TestimonialsBlue />
      <TestimonialsWhite /> 
      
    </>
  )
}
